[workspace]
resolver = "2"

members = [
    'node',
    'pallets/*',
    'pallets/groupsign/canned-benchmarks',
    'runtime',
]

[profile.release]
panic = 'unwind'
rpath = false
# opt size:
# lto = "thin"
# opt-level = 's'
